theme: jekyll-theme-hacker
title: Jawad Tanana
decription: Mechatronic Engineering and Computer Science
description: *"It's not about being the best, it's about being BETTER than you were yesterday."*


