title: Jawad Tanana
description: It's not about being the best, it's about being BETTER than you were yesterday.
show_downloads: true
google_analytics: G-9WGD8NXVTS
theme: jekyll-theme-cayman
timezone: Australia/Sydney
